### ISSUE TITLE
Adding type annotations?

### ISSUE THREAD

**Issue by takeda** [aio-libs/async-lru#432] opened 2022-07-10 23:32 UTC
Can type annotations be added to this module.

In https://github.com/aio-libs/async-lru/issues/70 it was mentioned that they couldn't be used as there was no mechanism for decorators. I don't believe that's true anymore.

**Comment by terala** [comment] 2022-08-22 00:07
This helped me: Create a `stubs/async_lru.pyi` file with these contents.

```python
"""Type hints for async_lru module"""

from typing import Any, Callable

# pylint: disable=unused-argument
def alru_cache(fn: Callable[..., Any] | None = ..., maxsize: int = ...,
               typed: bool = ..., *, cache_exceptions: bool = ...) -> Callable[..., Any]: ...
```

**Comment by Tinche** [comment] 2023-01-17 17:49
Here are more modern stubs:
```python
from typing import Any, Awaitable, Callable, ParamSpec, TypeVar, overload

P = ParamSpec("P")
T = TypeVar("T", bound=Awaitable)

@overload
def alru_cache(
    *, maxsize: int = ..., typed: bool = ..., cache_exceptions: bool = ...
) -> Callable[[Callable[P, T]], Callable[P, T]]: ...
@overload
def alru_cache(
    fn: Callable[P, T],
    *,
    maxsize: int = ...,
    typed: bool = ...,
    cache_exceptions: bool = ...
) -> Callable[P, T]: ...

```

**Comment by takeda** [comment] 2023-01-24 01:00
Any idea if these annotations could be integrated into the code so no stubs would be needed?

**Comment by gitpushdashf** [comment] 2023-02-08 23:57
Getting type hints in this repo would be great!

I'm having issues with the most recent stub hints. Not quite sure why. Using pyright.

```
stubs/async_lru.pyi:5:24 - error: Expected type arguments for generic class "Awaitable" (reportMissingTypeArgument)
```

**Comment by asvetlov** [comment] 2023-02-18 21:36
The library has stubs now out-of-the-box.
Stubs don't support ParamSpec yet (as @Tinche mentioned) because typeshed should support them for `functools.partial` and `functools.partialmethod`.

I plan to fix typeshed first, wait for the new mypy release, and update async_lru after it.
async-lru 2.0 will be released soon with `Callable[..., _R]` styled annotations.

**Closed by asvetlov** 2023-02-18 21:36 UTC

**Comment by lucasgadams** [comment] 2023-03-05 23:23
When I use the decorator I lose my type checks on the decorated function. I think this could be avoided if we use the `wraps` function from `functools`. At least in my own decorators this works well. I am using pywright

**Comment by lucasgadams** [comment] 2023-03-05 23:35
Hmm i notice that functools `lru_cache`  also breaks my typing. The issue is it no longer recognizes the required argument inputs for the decorated functions.
